### PR TITLE
Add support for Azure, OpenAI, Palm, Anthropic, Cohere Models - using litellm

### PR DESCRIPTION
**Pull request by ishaan-jaff**
Addresses https://github.com/piercefreeman/gpt-json/issues/29 

I'm the maintainer of litellm https://github.com/BerriAI/litellm - a simple & light package to call OpenAI, Azure, Cohere, Anthropic, Replicate API Endpoints

This PR adds support for models from all the above mentioned providers 

Here's a sample of how it's used:

```
from litellm import completion, acompletion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# async openai
response = acompletion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
Hi @piercefreeman can you take a look at this ? if the initial commit looks good, happy to add tests too 😊

**Comment by ishaan-jaff** [comment]
Hi @piercefreeman what was litellm missing to be useful to you? Any feedback here would be helpful

**Comment by piercefreeman** [comment]
Hey @ishaan-jaff, thanks for the PR. Have been thinking about the best way to handle this case for awhile now. My hesitation with a compatibility layer between models is being able to appropriately capture the nuance of getting true JSON-output from the different architectures. OpenAI's new response_format `{ type: "json_object" }` for instance isn't mirrored in most of the other language models out there.

Another consideration is to keep the default dependencies of gpt-json pretty lean, so it just pulls in openai's official library along with the necessary tokenization utilities. This seems a reasonable default behavior both because it's a gpt focused library and given its production usage, to minimize overall package size.

If you have some thoughts on the best approach to encourage json compatibility across the board, my suggestion would be to integrate litellm as a possible model backend and have a separate extras package published that pulls in its dependencies. What do you think?

**Comment by piercefreeman** [comment]
Closing for now, feel free to re-open.

**Pull request closed without merging**
